class AddSuits < ActiveRecord::Migration[5.2]
  def up
    Suit.create(name: "RX-78-2 Gundam", cost: 400)
    Suit.create(name: "Barbatos Lupus", cost: 400)
    Suit.create(name: "Freedom Gundam", cost: 400)
    Suit.create(name: "GP02 Gundam Physallis", cost: 400)
    Suit.create(name: "Gundam Gp03 Stamen", cost: 400)
    Suit.create(name: "G-Self", cost: 400)
    Suit.create(name: "Perfect Strike Gundam", cost: 400)
    Suit.create(name: "Providence Gundam", cost: 400)
    Suit.create(name: "Full Armor Gundam", cost: 400)
    Suit.create(name: "Psycho Zaku", cost: 400)
    Suit.create(name: "Atlas Gundam", cost: 400)
    Suit.create(name: "Tallgeese II", cost: 400)
    Suit.create(name: "Hyaku Shiki", cost: 400)
    Suit.create(name: "Gundam Crossbone X-1 Kai", cost: 400)
    Suit.create(name: "Gundam Crossbone X-3", cost: 400)
    Suit.create(name: "Phantom Gundam", cost: 400)
    Suit.create(name: "Zeong", cost: 400)
    Suit.create(name: "Gundam ZZ", cost: 400)
    Suit.create(name: "Unicorn Gundam 02 Banshee", cost: 400)
    Suit.create(name: "Baund Doc", cost: 400)
    Suit.create(name: "Gundam F91", cost: 400)
    Suit.create(name: "Gottrlatan", cost: 400)
    Suit.create(name: "Pale Rider (Ground Type)", cost: 400)
    Suit.create(name: "Alvaaron", cost: 400)
    Suit.create(name: "Zeydra", cost: 400)
    Suit.create(name: "Gundam Age-2", cost: 400)
    Suit.create(name: "Hot Scramble Gundam", cost: 500)
    Suit.create(name: "Zeta Gundam", cost: 500)
    Suit.create(name: "The-O", cost: 500)
    Suit.create(name: "Full-Armor ZZ", cost: 500)
	  Suit.create(name: "Qubeley", cost: 500)
	  Suit.create(name: "Nu Gundam", cost: 500)
	  Suit.create(name: "Sazabi", cost: 500)
	  Suit.create(name: "Hi-Nu Gundam", cost: 500)
	  Suit.create(name: "Nightingale", cost: 500)
	  Suit.create(name: "V2 Gundam", cost: 500)
	  Suit.create(name: "Unicorn Gundam", cost: 500)
	  Suit.create(name: "Sinanju", cost: 500)
	  Suit.create(name: "Wing Gundam Zero (TV Ver.)", cost: 500)
	  Suit.create(name:	"Gundam Epyon", cost: 500)
	  Suit.create(name:	"Turn A Gundam", cost: 500)
	  Suit.create(name: "Turn X", cost: 500)
	  Suit.create(name: "Crossbone Gundam X1 Full Cloth", cost: 500)
	  Suit.create(name: "G-self Perfect Pack", cost: 500)
	  Suit.create(name:	"God Gundam", cost: 500)
	  Suit.create(name: "Master Gundam", cost: 500)
	  Suit.create(name: "Char Custom Gelgoog", cost: 300) 
    Suit.create(name: "Gouf", cost: 300) 
    Suit.create(name: "Gyan", cost: 300) 
    Suit.create(name: "Gundam Mk-II", cost: 300) 
    Suit.create(name: "Gundam Mk-II (Titans)", cost: 300) 
    Suit.create(name: "Messala", cost: 300) 
    Suit.create(name: "Gabthley", cost: 300) 
    Suit.create(name: "Qubeley Mk-II", cost: 300) 
    Suit.create(name: "Jagd Doga", cost: 300) 
    Suit.create(name: "Delta Plus", cost: 300) 
    Suit.create(name: "Jesta", cost: 300) 
    Suit.create(name: "Kshatriya", cost: 300) 
    Suit.create(name: "Berga Giros", cost: 300) 
    Suit.create(name: "Gundam Deathscythe Hell", cost: 300) 
    Suit.create(name: "Gundam Heavyarms Kai", cost: 300) 
    Suit.create(name: "Gundam Sandrock Kai", cost: 300) 
    Suit.create(name: "Gundam Altron", cost: 300) 
    Suit.create(name: "Tallgeese", cost: 300) 
    Suit.create(name: "Corin’s Kapool", cost: 300) 
    Suit.create(name: "Gold Sumo", cost: 300) 
    Suit.create(name: "Strike Gundam", cost: 300) 
    Suit.create(name: "Forbidden Gundam", cost: 300) 
    Suit.create(name: "Raider Gundam", cost: 300) 
    Suit.create(name: "Aegis Gundam", cost: 300) 
    Suit.create(name: "Duel Gundam Assault Shroud", cost: 300) 
    Suit.create(name: "Blitz Gundam", cost: 300) 
    Suit.create(name: "Buster Gundam", cost: 300) 
    Suit.create(name: "Gundam Exia", cost: 300) 
    Suit.create(name: "Gundam Dynames", cost: 300) 
    Suit.create(name: "Gundam Kyrios", cost: 300) 
    Suit.create(name: "Gundam Virtue", cost: 300) 
    Suit.create(name: "Gundam Throne Eins", cost: 300) 
    Suit.create(name: "Gundam Throne Zwei", cost: 300) 
    Suit.create(name: "Gundam Throne Drei", cost: 300) 
    Suit.create(name: "Graham’s Union Flag Custom", cost: 300) 
    Suit.create(name: "G-Arcane (Full Dress)", cost: 300) 
    Suit.create(name: "Mack Knife (Mask’s Unit)", cost: 300) 
    Suit.create(name: "Gundam Barbatos", cost: 300) 
    Suit.create(name: "Gundam Kimaris Trooper", cost: 300) 
    Suit.create(name: "Gundam Gusion Rebake", cost: 300) 
    Suit.create(name: "Gundam Ez8", cost: 300) 
    Suit.create(name: "Gouf Custom", cost: 300) 
    Suit.create(name: "Slave Wraith", cost: 300) 
    Suit.create(name: "Vincent’s High Mobility Gelgoog", cost: 300) 
    Suit.create(name: "Gundam “Zephyranthes” Full Burnern", cost: 300) 
    Suit.create(name: "Crossbone Gundam X-2 Kai", cost: 300) 
    Suit.create(name: "Gundam AGE-1", cost: 300) 
    Suit.create(name: "Farsia", cost: 300) 
    Suit.create(name: "Zaku I (Gellert Schmeisser Custom)", cost: 300) 
    Suit.create(name: "Mudrock Gundam", cost: 300) 
    Suit.create(name: "Pixie (Fred’s unit)", cost: 300) 
    Suit.create(name: "Build Strike (Full Package)", cost: 300)
    Suit.create(name: "Guntank", cost: 200) 
    Suit.create(name: "Doan’s Zaku II", cost: 200)
    Suit.create(name: "Char Custom Zaku II", cost: 200) 
    Suit.create(name: "Dom", cost: 200) 
    Suit.create(name: "Rick Dias", cost: 200) 
    Suit.create(name: "Metthuss", cost: 200) 
    Suit.create(name: "Nemo", cost: 200) 
    Suit.create(name: "Marasai", cost: 200) 
    Suit.create(name: "Hi-Zack", cost: 200) 
    Suit.create(name: "Re-GZ", cost: 200) 
    Suit.create(name: "Rezel", cost: 200) 
    Suit.create(name: "Vigna Ghina", cost: 200) 
    Suit.create(name: "Gun EZ", cost: 200) 
    Suit.create(name: "Kapool", cost: 200) 
    Suit.create(name: "Silver Sumo", cost: 200) 
    Suit.create(name: "Tieren Taozi", cost: 200) 
    Suit.create(name: "GN-X", cost: 200) 
    Suit.create(name: "Ground Gundam", cost: 200) 
    Suit.create(name: "GM Custom", cost: 200) 
    Suit.create(name: "GM Cannon II", cost: 200) 
    Suit.create(name: "GM Sniper II (White Dingo Custom)", cost: 200)
  end
  
  def down
    Suit.delete_all
  end
end
